version: "3.9"

services:
    db:
        image: neo4j:latest
        restart: unless-stopped
        environment:
            NEO4J_PLUGINS: '["apoc"]'
            apoc.export.file.enabled: 'true'
            apoc.import.file.enabled: 'true'
            apoc.import.file.use_neo4j_config: 'true'
            NEO4J_dbms_security_procedures_unrestricted: 'apoc.*'
        env_file:
            - .env
        expose:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - data:/data
    realm:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        image: jacoblincool/unicourse-realm:latest
        restart: unless-stopped
        env_file:
            - .env
        expose:
            - "3000:3000"
    tunnel:
        image: cloudflare/cloudflared:latest
        command: "tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}"

volumes:
    data: {}
