name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    version:
        name: Version
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Create Release Pull Request or Release
              id: changesets
              uses: changesets/action@v1
              with:
                  title: Release
                  commit: bump versions
                  publish: docker buildx bake --set "*.platform=linux/arm64/v8,linux/amd64" --push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
